<a href="https://colab.research.google.com/github/anirudhnayak1308/Netzwerk/blob/main/DiabetesProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [15]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [16]:
df.duplicated().sum()

0

In [3]:
#intializing variables
X = df[['Pregnancies','Glucose','BloodPressure','SkinThickness', 'Insulin','BMI','DiabetesPedigreeFunction','Age']]
y = df['Outcome']


In [5]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [6]:
#Splitting the dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
print('Split Done')

Split Done


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [7]:
#training model
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()
reg.fit(X_train,y_train)
print('Algorithm fit success !!')

Algorithm fit success !!


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [11]:
y_pred = reg.predict(X_test)

In [12]:
y_pred

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0])

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[93 12]
 [26 23]]


0.7532467532467533

In [19]:
output = reg.predict([[1,85,66,29,0,26.6,0.351,31]])
output

array([0])

Asking input from user

In [22]:
preg = int(input('No of Pregnancies :'))
glucose = int(input('Glucose level :'))
bp = int(input('BloodPressure level :'))
st = int(input('Skin thickness : '))
insulin = int(input('Insulin level :'))
bmi = float(input('BMI level :'))
DPF = float(input('DiabetesPedigreeFunction :'))
age = int(input('Age :'))

#output prediciton to the input
op = reg.predict([[preg,glucose,bp,st,insulin,bmi,DPF,age]])
print('Outcome is {} if they are having {} Pregnancies, {} glucose level, {} BP, {} skin thickness, {} insulin, {} BMI,{}  DiabetesPedigreeFunction and age is {}'.format(output[0] if output else '0',preg,glucose,bp,st,insulin,bmi,DPF,age))

No of Pregnancies :5
Glucose level :70
BloodPressure level :58
Skin thickness : 0
Insulin level :10
BMI level :45.2
DiabetesPedigreeFunction :22.5
Age :25
Outcome is 0 if they are having 5 Pregnancies, 70 glucose level, 58 BP, 0 skin thickness, 10 insulin, 45.2 BMI,22.5  DiabetesPedigreeFunction and age is 25
