<a href="https://colab.research.google.com/github/anirudhnayak1308/Netzwerk/blob/main/Logistic_socialAd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [3]:
#read the data
data = pd.read_csv('/content/Social_network.csv')

In [ ]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [4]:
#initializing variables

x = data.drop(['Purchased'], axis = 1)
y = data['Purchased'].values.reshape(-1,1)

In [5]:
#splitting the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state=1)

In [6]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [7]:
from sklearn.linear_model import LogisticRegression
cls = LogisticRegression()
cls.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
y_pred = cls.predict(x_test)

In [9]:
y_pred

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
cm 


array([[43,  5],
       [10, 22]])

In [11]:
accuracy_score(y_test,y_pred)

0.8125

In [21]:
output = cls.predict(sc.transform([[35,20000]]))
output

array([0])

In [24]:
print("Example for logistic Regression : ")
age=int(input("Age : "))
salary=int(input("Salary : "))
print('purchase result is {} if person is aged {},and his salary is {}, '.format(output[0] if output else 'not',age,salary,output))




Example for logistic Regression : 
Age : 35
Salary : 20000
purchase result is not if person is aged 35,and his salary is 20000, 
