<a href="https://colab.research.google.com/github/anirudhnayak1308/Netzwerk/blob/main/Knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Knn Algorithm

In [1]:
#importing the libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
#importing the dataset
df = pd.read_csv('/content/Social_network.csv')
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

#initializing the x and y

In [3]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

Splitting data into training and testing

In [6]:
from sklearn.model_selection import train_test_split
x_test, x_train, y_test, y_train = train_test_split(x,y,test_size=0.2,random_state= 2)

Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [8]:
x_train

array([[-0.74651519,  0.33929263],
       [-1.48154554, -1.59952242],
       [-0.01148485, -0.52883351],
       [-0.74651519,  0.10779233],
       [ 1.55045463, -0.03689536],
       [ 0.90730308, -1.48377227],
       [-1.29778795,  0.3103551 ],
       [-0.83839399, -1.13652181],
       [ 0.26415153, -0.32627074],
       [-0.10336364,  1.58360677],
       [-1.20590916, -1.39695965],
       [-1.38966674, -1.2812095 ],
       [-0.47087881,  1.32316893],
       [ 0.7235455 ,  0.22354248],
       [-0.19524244, -0.35520828],
       [-0.37900002, -0.81820889],
       [-1.66530312, -0.03689536],
       [ 2.10172739, -0.84714643],
       [ 1.45857584,  0.02097972],
       [-1.02215157, -0.81820889],
       [-0.01148485,  0.19460494],
       [ 0.7235455 , -0.76033381],
       [-0.6546364 , -0.26839567],
       [-0.10336364, -1.10758427],
       [-1.11403037,  0.25248002],
       [ 0.7235455 , -1.13652181],
       [ 0.7235455 , -1.42589719],
       [ 0.26415153, -0.41308336],
       [ 0.6316667 ,

Training using Knn alogorithm

In [9]:
from sklearn.neighbors import KNeighborsClassifier
cls = KNeighborsClassifier(n_neighbors=5)
cls.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

#Testing the model

In [10]:
y_pred = cls.predict(x_test)

Checking the accuracy

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print('The accuracy is :', accuracy_score(y_test,y_pred))

[[187  22]
 [ 10 101]]
The accuracy is : 0.9


#Predicting for new value

In [22]:
output = cls.predict([[25, 22000]])
output

array([1])

#Asking input from the user


In [23]:
print('User Input')
age = float(input('Enter age :'))
Esalary = float(input('Enter salary :'))
output = cls.predict([[age,Esalary]])
print('The result is {} if person is aged {} and his salary is {}'.format(output[0] if output else 'Not',age,Esalary) )

User Input
Enter age :19
Enter salary :19000
The result is 1 if person is aged 19.0 and his salary is 19000.0
